export const SET_LOADING = 'SET_LOADING'

export const SET_ERROR = 'SET_ERROR'

export const CLEAR_ERROR = 'CLEAR_ERROR'

export const GET_PRODUCTS = 'GET_PRODUCTS'

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'

export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'

export const PAY_SHOPPING_CART = 'PAY_SHOPPING_CART'

export const SHOW_MINI_CART = 'SHOW_MINI_CART'

export const CLOSE_MINI_CART = 'CLOSE_MINI_CART'
